export default {
  UPDATE_WX_PARAMS: 'UPDATE_WX_PARAMS',
  UPDATE_CONTACT_LIST: 'UPDATE_CONTACT_LIST',
  UPDATE_ARTICLE_LIST: 'UPDATE_ARTICLE_LIST',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_CHAT_SET: 'UPDATE_CHAT_SET',
}