export default {
  CONTACTFLAG_CONTACT            : 1,
  CONTACTFLAG_CHATCONTACT        : 2,
  CONTACTFLAG_CHATROOMCONTACT    : 4,
  CONTACTFLAG_BLACKLISTCONTACT   : 8,
  CONTACTFLAG_DOMAINCONTACT      : 16,
  CONTACTFLAG_HIDECONTACT        : 32,
  CONTACTFLAG_FAVOURCONTACT      : 64,
  CONTACTFLAG_3RDAPPCONTACT      : 128,
  CONTACTFLAG_SNSBLACKLISTCONTACT: 256,
  CONTACTFLAG_NOTIFYCLOSECONTACT : 512,
  CONTACTFLAG_TOPCONTACT         : 2048,
}